blog/2023-06-17-ratify-notary.mdx, docusaurus.config.js, package.json
fix #2 
Preview it at https://deploy-preview-3--ratify-dev.netlify.app/
=> chore: update version and blog URL

docs/quickstarts/ratify-on-azure.md
porting over Xinhe's Change at https://github.com/deislabs/ratify/pull/1090/files
=> docs: fix quickstart incorrect file reference

docs/what-is-ratify.mdx
remove non production notice in anticipation of 1.0 release
=> docs: remove non production notice

docs/quick-start.mdx, docs/quickstarts/quickstart-manual.md, docs/quickstarts/ratify-high-availability.md
- Removes manual quick start steps from top level quick start
- replaces with helmfile installation steps
- Adds separate manual quick start steps doc
=> docs: add manual quick start steps

docs/reference/errors.md
- Updates error message doc for verifier signatures
- Corresponds to https://github.com/deislabs/ratify/pull/1129
=> docs: update verifier plugin error type and message

docs/troubleshoot/verifier/notation.md
Add TSG for common errors from notation verifiers.
This is resolving issue: https://github.com/deislabs/ratify/issues/1100
=> docs: add notation verifier tsg

docs/quickstarts/ratify-with-venafi.md
Support for Venafi notation plugin as a Verifier.
=> Venafi notation plugin support - Updated

docs/external plugins/Verifier/vulnerabilityreport.md
- small update for bash shell compat
- remove extra sig flag in basic scenario
- remove layer media type specification 
- pin constraint and constraint template download links to v1.1.0
=> fix: vuln report doc

docs/reference/verification-result-version.md, docs/reference/verifier.md
Introduced the verifier type.
Verifier type will be supported in v1.1.0, backward compatible.
=> doc: introduce the verifier type

docs/quickstarts/developer-getting-started.md, docs/quickstarts/quickstart-manual.md, docs/quickstarts/ratify-high-availability.md, docs/quickstarts/ratify-on-aws.md, docs/quickstarts/ratify-on-azure.md, docs/quickstarts/ratify-with-aws-signer.md, docs/quickstarts/ratify-with-venafi.md, versioned_docs/version-1.1/quickstarts/developer-getting-started.md, versioned_docs/version-1.1/quickstarts/quickstart-manual.md, versioned_docs/version-1.1/quickstarts/ratify-high-availability.md, versioned_docs/version-1.1/quickstarts/ratify-on-aws.md, versioned_docs/version-1.1/quickstarts/ratify-on-azure.md, versioned_docs/version-1.1/quickstarts/ratify-with-aws-signer.md, versioned_docs/version-1.1/quickstarts/ratify-with-venafi.md
Updates docs in next and 1.1 release to add external data provider cache ttl override. This was added in 3.14.
=> fix: update GK docs to add response cache ttl override

docs/reference/crds/verifiers.md, versioned_docs/version-1.1/reference/crds/verifiers.md
We updated the Verifier CR to include the namespaced name in Ratify 1.1. This PR updates the notation verifier to use the  namespaced certStore. The description is already up to date.
=> Update notation sample in verifiers.md

docusaurus.config.js
=> added algolia search

docs/reference/multi-tenancy.md
Add new line above the table so that it can be rendered correctly.
=> fix: fix broken table

docs/reference/multi-tenancy.md
Add videos to multi-tenancy doc.
=> docs: add videos

docs/reference/ratify-framework-overview.md, versioned_docs/version-1.0/reference/ratify-framework-overview.md, versioned_docs/version-1.1/reference/ratify-framework-overview.md, versioned_docs/version-1.2/reference/ratify-framework-overview.md
=> docs: fix some typo

docs/reference/deprecation-notice.md
Add deprecation notice for Ratify.
It adds the features that are announced as deprecated in v1.x and will be removed in v2.0. More deprecating features could be added in this notice.
Will close: https://github.com/ratify-project/ratify/issues/1409
=> docs: add deprecation notice for v1

docs/quickstarts/ratify-on-azure.md
This PR aims to fix the issue #107 to resolve the problems with the instructions on setting up Ratify on Azure.
=> docs: update instructions for setting up ratify on Azure

docs/plugins/verifier/notation.md
Add more information about `tsa` and trust store types.
Correct the concept naming replace `Time-stamping` with `timestamping`
=> docs: add more information about tsa

docs/quickstarts/ratify-on-azure.md, versioned_docs/version-1.2/quickstarts/ratify-on-azure.md, versioned_docs/version-1.3/quickstarts/ratify-on-azure.md
Updates:
- Fix format issues
Signed-off-by: Yi Zha <yizha1@microsoft.com>
=> docs: fix format issues

docs/quickstarts/ratify-high-availability.md, src/components/Header/Header.jsx, versioned_docs/version-1.0/quickstarts/ratify-high-availability.md, versioned_docs/version-1.1/quickstarts/ratify-high-availability.md, versioned_docs/version-1.2/quickstarts/ratify-high-availability.md, versioned_docs/version-1.3/quickstarts/ratify-high-availability.md
Preview: https://deploy-preview-126--ratify-dev.netlify.app/
=> docs: update get started link and add experimental feature status

docs/plugins/verifier/notation.md
Add CRL description into notation verifier description, sharing more context about the revocation check workflow.
=> docs: update CRL description

docs/quickstarts/ratify-with-venafi.md
Updated Venafi documentation to support KeyManagementProvider
=> docs: update Venafi quick start

docs/quick-start.mdx
Update helmfile path in getting started.
=> fix: update helmfile path for getting started
